### ISSUE TITLE
‘_imu2body’ was not declared in this scope

### ISSUE THREAD

**Issue by gustavoneves12** [rock-slam/slam-orogen-orientation_estimator#1]
I am trying to compile this package, but I am getting the error below:

~/rock-robotics/slam/orogen/orientation_estimator/tasks/IKF.cpp:27:10: error: ‘_imu2body’ was not declared in this scope
         if (!_imu2body.get(ts, imu2body))

I think this property was not declared in the orogen file.

**Comment by saarnold** [comment]
This is not a property but a transformer::Transformation.
It is defined in line 152 in the orientation_estimator.orogen

```
    transformer do
        transformation("imu", "body")
        align_port("imu_samples", 0.01)
        max_latency(0.05)
    end
```

Do you have any local changes that could cause this issue?

**Comment by gustavoneves12** [comment]
I did not changes. I just did autoproj update and I got this error.

**Comment by saarnold** [comment]
You can try to do a amake --rebuild inside of slam/orogen/orientation_estimator

**Comment by gustavoneves12** [comment]
Ok, thanks!
It's working now!!
